version: '3.8'

services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - JWT_SECRET=your-jwt-secret-here
      - ADMIN_JWT_SECRET=your-admin-jwt-secret-here
      - APP_KEYS=key1,key2,key3,key4
      - API_TOKEN_SALT=your-api-token-salt-here
      - TRANSFER_TOKEN_SALT=your-transfer-token-salt-here
    volumes:
      - strapi_data:/app/server/.tmp
      - strapi_uploads:/app/server/public/uploads
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:1337/admin"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nextjs:
    build:
      context: .
      target: client-build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_STRAPI_URL=http://strapi:1337
    depends_on:
      strapi:
        condition: service_healthy
    command: ["sh", "-c", "cd client && yarn start"]

volumes:
  strapi_data:
  strapi_uploads:
