services:
  strapi:
    build: .
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - JWT_SECRET=your-jwt-secret-change-this-in-production
      - ADMIN_JWT_SECRET=your-admin-jwt-secret-change-this-in-production
      - APP_KEYS=key1-change-this,key2-change-this,key3-change-this,key4-change-this
      - API_TOKEN_SALT=your-api-token-salt-change-this-in-production
      - TRANSFER_TOKEN_SALT=your-transfer-token-salt-change-this-in-production
    volumes:
      - strapi_data:/app/server/.tmp
      - strapi_uploads:/app/server/public/uploads
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:1337/admin"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  strapi_data:
    driver: local
  strapi_uploads:
    driver: local
