
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Header, Footer } from "@/components/layout";
import { getGlobalPageData } from "@/data/loaders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getGlobalPageData();
  if (!data) notFound();

  const { topNav, footer } = data.data;

  return (
    <div>
      <Header data={topNav} />
      {children}
      <Footer data={footer} />
    </div>
  );
}
